version: '3'
services:
  angularfront:
    container_name: angularimg
    build: .
    image: angularimg:v1
    ports:
      - "4200:80"
    networks:
      - device_demo_net

networks:
  device_demo_net:
    external: true
