version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: elefant123
      POSTGRES_DB: energydb
    ports:
      - "5435:5435"
    networks:
      device_demo_net:
        ipv4_address: 172.19.0.10  # Adresa IP dorită pentru containerul PostgreSQL


  spring-app:
    build:
      context: .  # Directorul în care se află Dockerfile-ul aplicației Spring Boot
    ports:
      - "8082:8082"
    environment:
      DB_IP: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: elefant123
      DB_DBNAME: energydb
    depends_on:
      - postgres
    networks:
      device_demo_net:
        ipv4_address: 172.19.0.11


networks:
  device_demo_net:
    external: true
